server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  servlet:
    context-path: /app