spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:mysql://localhost:3306/highway_ticket_managment?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  servlet:
    context-path: /app
